export enum GameState {
    LOBBY = 'LOBBY',    
    IN_PROGRESS = 'IN_PROGRESS',
    CORRECT_ANSWER = 'CORRECT_ANSWER',
    IN_INCORRECT_ANSWER = 'IN_INCORRECT_ANSWER',
    SHOWING_SCORES = 'SHOWING_SCORES',
    GAME_OVER = 'GAME_OVER'
}