export enum QuizScreenState {
    WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
    STARTING_QUIZ = 'STARTING_QUIZ',
    SHOWING_QUESTION = 'SHOWING_QUESTION',
    SHOWING_ANSWER = 'SHOWING_ANSWER',
    SHOWING_SCORES = 'SHOWING_SCORES',
    QUIZ_OVER = 'QUIZ_OVER'
}